tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

# sshfs dependes on osxfuse and it is required to be installed first
cask "osxfuse"
brew "arp-scan"
brew "asciinema"
brew "autossh"
brew "bash"
brew "bat"
brew "brotli"
brew "cloc"
brew "coreutils"
brew "diff-so-fancy"
brew "fd"
brew "ffmpeg"
brew "findutils"
brew "fzf"
brew "gist"
brew "git"
brew "glances"
brew "gnu-sed"
brew "gnupg"
brew "htop"
brew "httpie"
brew "httpstat"
brew "hub"
brew "hyperfine"
brew "imagemagick"
brew "jq"
brew "lbzip2"
brew "lolcat"
brew "lynx"
brew "m-cli"
brew "mas"
brew "micro"
brew "mycli"
brew "mysql", restart_service: :changed
brew "ncdu"
brew "neofetch"
brew "neovim"
brew "nmap"
brew "node"
brew "noti"
brew "nyancat"
brew "pastel"
brew "pigz"
brew "pinentry-mac"
brew "pv"
brew "ranger"
# Dependency of tmux-yank
brew "reattach-to-user-namespace"
brew "redis"
brew "ripgrep"
brew "rsync"
brew "ruby"
brew "shellcheck"
brew "shpotify"
brew "slurm"
brew "sshfs"
brew "thefuck"
brew "tig"
brew "tldr"
brew "tmux"
brew "trash"
brew "tree"
brew "vegeta"
brew "wget"
brew "yarn"
brew "z"
brew "zstd"

cask "alfred"
cask "atom"
cask "bettertouchtool"
cask "betterzip"
cask "firefox"
cask "firefox-developer-edition"
cask "firefox-nightly"
cask "flux"
cask "font-fira-code"
cask "font-firacode-nerd-font"
cask "google-chrome"
cask "grandperspective"
cask "handbrake"
cask "hex-fiend"
cask "iina"
cask "intel-power-gadget"
cask "iterm2"
cask "kap"
cask "keycastr"
cask "macs-fan-control"
cask "mactracker"
cask "mysqlworkbench"
cask "postman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "sizeup"
cask "spotify"
cask "superduper"
cask "visual-studio-code"
cask "vlc"
cask "vnc-viewer"

mas "Keynote", id: 409183694
mas "MiniPlay", id: 936243210
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Trello", id: 1278508951
mas "Unsplash Wallpapers", id: 1284863847
mas "Wipr", id: 1320666476
