tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "homebrew/services"
tap "rigellute/tap"
tap "teamookla/speedtest"

# sshfs depends on osxfuse and it is required to be installed first
cask "osxfuse"
brew "arduino-cli"
brew "arp-scan"
brew "asciinema"
brew "autossh"
brew "bash"
brew "bat"
brew "brotli"
brew "cmatrix"
brew "coreutils"
brew "cowsay"
brew "ddgr"
brew "diff-so-fancy"
brew "diskus"
brew "exa"
brew "fd"
brew "ffmpeg"
brew "findutils"
brew "fortune"
brew "fzf"
brew "gist"
brew "git"
brew "git-lfs"
brew "glances"
brew "gnu-sed"
brew "gnupg"
brew "hexyl"
brew "htop"
brew "httpie"
brew "httpstat"
brew "hub"
brew "hyperfine"
brew "imagemagick"
brew "jq"
brew "lbzip2"
brew "lolcat"
brew "lynx"
brew "m-cli"
brew "man-db"
brew "mas"
brew "mkcert"
brew "mycli"
brew "nano"
brew "ncdu"
brew "neofetch"
brew "neovim"
brew "nmap"
brew "node"
brew "noti"
# Required for mkcert to work in Firefox
brew "nss"
brew "nyancat"
brew "osx-cpu-temp"
brew "pastel"
brew "pigz"
brew "pinentry-mac"
brew "pstree"
brew "pv"
brew "ranger"
# Dependency of tmux-yank
brew "reattach-to-user-namespace"
brew "redis"
brew "ripgrep"
brew "rsync"
brew "shellcheck"
brew "shpotify"
brew "slurm"
brew "sshfs"
brew "thefuck"
brew "tig"
brew "tldr"
brew "tmux"
brew "tokei"
brew "trash"
brew "tree"
brew "vegeta"
brew "wakeonlan"
brew "watch"
brew "wget"
brew "yarn"
brew "z"
brew "zstd"
brew "rigellute/tap/spotify-tui"
brew "teamookla/speedtest/speedtest"

# Dependency of dbeaver-community
cask "adoptopenjdk"
cask "alfred"
cask "bettertouchtool"
cask "betterzip"
cask "cheatsheet"
cask "cinebench"
cask "dbeaver-community"
cask "docker"
cask "firefox"
cask "firefox-developer-edition"
cask "firefox-nightly"
cask "flux"
cask "font-fira-code"
cask "font-firacode-nerd-font"
cask "google-chrome"
cask "grandperspective"
cask "handbrake"
cask "hex-fiend"
cask "iina"
cask "intel-power-gadget"
cask "iterm2"
cask "kap"
cask "keycastr"
cask "macs-fan-control"
cask "mactracker"
cask "mark-text"
cask "mysqlworkbench"
cask "postman"
cask "protonvpn"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "sizeup"
cask "soundflower"
cask "spotify"
cask "sublime-text"
cask "superduper"
cask "tunnelblick"
cask "visual-studio-code"
cask "vlc"
cask "vnc-viewer"

mas "Amphetamine", id: 937984704
mas "Dato", id: 1470584107
mas "DuckDuckGo Privacy Essentials", id: 1482920575
mas "Keynote", id: 409183694
mas "Kiwi for Gmail", id: 986304488
mas "MiniPlay", id: 936243210
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Trello", id: 1278508951
mas "Unsplash Wallpapers", id: 1284863847
mas "Wipr", id: 1320666476
# Required for building native node addons
mas "Xcode", id: 497799835
